name: Metrics Facts

on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"
    
  push:
    branches:
      - master
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Mildly interesting facts
        uses: lowlighter/metrics@latest
        with:
          filename: SVG/metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          config_timezone: Europe/Paris
