name: Metrics ISO Calender Full Year

on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"
    
  push:
    branches:
      - master
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: SVG/metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year