name: Metrics Most Used Languages

on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"
    
  push:
    branches:
      - master
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Featured star list languages
        uses: lowlighter/metrics@latest
        with:
          filename: SVG/metrics.plugin.starlists.languages.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: Awesome
